server:
  port: 8443
  context-path:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 335500
  jpa:
    hibernate:
      ddl-auto: update
      dialect: PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect